### ISSUE TITLE
[TypeError: fetch failed] { cause: [Error: AggregateError] }

### ISSUE THREAD

**Issue by haopengsong** [blrchen/chatgpt-minimal#10]
Hello! Thanks for sharing this awsome UI.
I am new to Nextjs and React and encounterred issue when tried to run it locally.
Basically, when I started the application with :

**'npm run dev'**

and made requests with prompts, I got errors said :

**[TypeError: fetch failed] { cause: [Error: AggregateError] }**

and under the network tab, the frontend received error with **code 500.**

Can you help me with this issue? Thanks so much.

![_20231207180059](https://github.com/blrchen/chatgpt-minimal/assets/19417094/f95f3c31-b16b-499d-a108-0b258baad934)

![20231207180155](https://github.com/blrchen/chatgpt-minimal/assets/19417094/f698af88-fea2-4719-8043-0ae3d40fccb6)

**Comment by haopengsong** [comment]
The openai_api key works fine.

**Comment by blrchen** [comment]
Thank you for reaching out. Unfortunately, I'm unable to reproduce the issue you're experiencing. If the OpenAI key is correctly set, the chat should function properly. Conversely, if the key is invalid or not set, an error message "Unauthorized" with a status code of 401 will appear in the console log.

To troubleshoot further, you might want to set a breakpoint in chat-completion.ts to investigate why the fetch from OpenAI chat completion endpoint is failing.
