### ISSUE TITLE
can you show me, how you deploy this project to vercel?

### ISSUE THREAD

**Issue by ozbillwang** [blrchen/chatgpt-minimal#9]
I did it, but after type the question, no responds

**Comment by blrchen** [comment]
Please ensure the Environment Variables in the Vercel admin dashboard are correctly set. If you're using OpenAI ChatGPT, set the `OPENAI_API_KEY`. For Azure OpenAI, set the `AZURE_OPENAI_API_BASE_URL`, `AZURE_OPENAI_API_KEY` and `AZURE_OPENAI_DEPLOYMENT`.

If you still not get chat response, please share error log displayed in Vercel admin dashboard.
